//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Availability { get; set; }
        public int MenuId { get; set; }
        public int ItemId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
